; 起動から QUICK 立ち上げまでを自動で流す。日付は今日の月日 + 1979 年 (この TOPS-10 は 2000 年問題を持つ)
do /opt/ini/common.ini
expect "\r\n" send "SYSTEM\r"; continue
expect "WHY RELOAD:" send  "SCHED\r"; continue
expect "DATE:" send  "%DATE_MMM%-%DATE_DD%-79\r"; continue
expect "TIME:" send  "%TIME_HH%%TIME_MM%\r"; continue
expect "STARTUP OPTION" send "QUICK\r"; continue
boot dpa
